[package]
name = "binmatch"
version = "1.2.0"
edition = "2021"
authors = ["DakotaGay <DakotaGay@disroot.org>"]
license = "AGPL-3.0-or-later"
description = "A simple binary pattern matching crate"
repository = "https://github.com/DakotaGay/binmatch"
readme = "README.md"
keywords = ["pattern-matching", "binary-data"]
categories = ["encoding"]

[dependencies]
thiserror = { version = "1.0.58", optional = true }

[features]
std = ["dep:thiserror"]
default = ["std"]
